/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentReviewRouteImport } from './routes/payment-review'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorklogsWorklogIdRouteImport } from './routes/worklogs/$worklogId'

const PaymentReviewRoute = PaymentReviewRouteImport.update({
  id: '/payment-review',
  path: '/payment-review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorklogsWorklogIdRoute = WorklogsWorklogIdRouteImport.update({
  id: '/worklogs/$worklogId',
  path: '/worklogs/$worklogId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-review': typeof PaymentReviewRoute
  '/worklogs/$worklogId': typeof WorklogsWorklogIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-review': typeof PaymentReviewRoute
  '/worklogs/$worklogId': typeof WorklogsWorklogIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-review': typeof PaymentReviewRoute
  '/worklogs/$worklogId': typeof WorklogsWorklogIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/payment-review' | '/worklogs/$worklogId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/payment-review' | '/worklogs/$worklogId'
  id: '__root__' | '/' | '/payment-review' | '/worklogs/$worklogId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentReviewRoute: typeof PaymentReviewRoute
  WorklogsWorklogIdRoute: typeof WorklogsWorklogIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-review': {
      id: '/payment-review'
      path: '/payment-review'
      fullPath: '/payment-review'
      preLoaderRoute: typeof PaymentReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worklogs/$worklogId': {
      id: '/worklogs/$worklogId'
      path: '/worklogs/$worklogId'
      fullPath: '/worklogs/$worklogId'
      preLoaderRoute: typeof WorklogsWorklogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentReviewRoute: PaymentReviewRoute,
  WorklogsWorklogIdRoute: WorklogsWorklogIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
